on: 
  repository_dispatch:
    types: [build-and-test-backend]
jobs: 
  docker:
    build-and-push-docker-image:
      needs: build-and-test-backend
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./simple-api
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp2:simple-api
          push: ${{ github.ref == 'refs/heads/main }}
      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          context: ./database
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp2:database
          push: ${{ github.ref == 'refs/heads/main }}
      - name: Build image and push httpd
        uses: docker/build-push-action@v2
        with:
        #push
          context: ./httpd
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp2:httpd
          push: ${{ github.ref == 'refs/heads/main }}
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{secrets.DOCKER_HUB_ACCESS_TOKEN }}

