name: CI devops 2021 EPF

on: [push]

jobs:
  build:
    build-and-test-app:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Build with Maven
          run: mvn --batch-mode --update-snapshots --file simple-api/pom.xml verify